### ISSUE TITLE
Can't reference any v2 release from go modules

### ISSUE THREAD

**Issue by alexellis** [ihippik/wal-listener#10]
Hi, thanks for wal-listener

I've been trying to add the latest v2 release you cut into a go.mod file.

The main issue is described here https://github.com/mattn/go-sqlite3/issues/812

To go to a v2 release, you need to update go.mod and append "/v2" to the name of the module. This bit me too when releasing a v2 of a simple Go library.

```
module wal-listener-example

go 1.18

require (
	github.com/ihippik/wal-listener v2.2.0
)
```

Error:

```
go.mod:7:2: require github.com/ihippik/wal-listener: version "v2.2.0" invalid: should be v0 or v1, not v2
```

Alex

**Comment by ihippik** [comment]
oops sorry man, didn't see your comment(

yep, my bad - I totally forgot about that.

how do you use the listener? what exactly are you importing?

**Comment by ihippik** [comment]
I fixed the module name

**Comment by alexellis** [comment]
Thank you. I get that you must also have a lot of notifications.

Incidentally, when you add `go 1.20` I'm pretty sure it forces anyone on Go 1.19 or 1.18 to change their Go version, but doesn't actually give you any gain. It just makes it worse for consumers.

We keep our OSS projects at a lower, more compatible version for go.mod and then build with whatever version makes sense (which is independent)

Alex
