### ISSUE TITLE
 ERROR: publication "pub_test" does not exist 

### ISSUE THREAD

**Issue by Andrewpqc** [ihippik/wal-listener#2]
I do sure that the publication "pub_test" exist, but WaitForReplicationMessage  method of jackc/pgx return a error that tell me "publication "pub_test" does not exist ". I'd appreciate if you could help.

**Comment by ihippik** [comment]
Forgot to mention this in the documentation. First you need to create a post:
```CREATE PUBLICATION "wal-listener" FOR ALL TABLES;```

But this must be done before the slot is created, since they will be connected.

ps. do it in the code, but you will have to change the name of the slot or delete the existing one
