### ISSUE TITLE
Question: works? 

### ISSUE THREAD

**Issue by josejuanmontiel** [ihippik/wal-listener#28]
Hi! Take my question as newby in this library :) ... i was playing with postgres and nats ... replication works in the slave postgres, but i can`t see logs of the replication in the library ... what i'm missing?

1. Maybe need to grant roles to replication user to "my_table"?
2. some extra parameter in https://www.postgresql.org/docs/current/sql-createpublication.html
3. Did you consider use https://github.com/jackc/pglogrepl ?

I'm going to continue playing with ... later i'll share my insights.

Very interesting library... a go alternative to java debezium (not binding to kafka connect)

**Comment by ihippik** [comment]
Hey @josejuanmontiel! 
did you check https://github.com/ihippik/wal-listener/blob/master/docker/docker-compose.yml , is it works for you?
I'll try from scratch and if something is not clear, I'll update the documentation
About pglogrepl - I was inspired by this library.
