### ISSUE TITLE
How to distinguish between NULL from empty string?

### ISSUE THREAD

**Issue by Andrewpqc** [ihippik/wal-listener#3]
This is a problem bothering me for a long time.  What's your opinion on this question?

**Comment by ihippik** [comment]
There is such a problem. I didn't need it, but I'll take a look at the protocol. I think this is being resolved.

**Comment by ihippik** [comment]
I pushed the changes to the master branch - try it now.

**Comment by Andrewpqc** [comment]
OK,Thanks
