### ISSUE TITLE
feat: health checks

### ISSUE THREAD

**Issue by jbergstroem** [ihippik/wal-listener#31]
It would be nice if `wal-listener` had a way of expressing health via a http endpoint or similar.

**Comment by ihippik** [comment]
thanks, good idea!
@jbergstroem do you think it should include checking some logic (for example, db connections)?

**Comment by jbergstroem** [comment]
> thanks, good idea! @jbergstroem do you think it should include checking some logic (for example, db connections)?

Optimally it would have two endpoints; one for [readiness](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes) and one for [liveness](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-command)

**Comment by emidander** [comment]
I want this as well for Kubernetes reasons - are you planing anything, or should I try to make a simple solution?

**Comment by jbergstroem** [comment]
> I want this as well for Kubernetes reasons - are you planing anything, or should I try to make a simple solution?

Feel free; I don't have time until EOW.

**Comment by ihippik** [comment]
sorry guys, was busy. working on it

**Comment by emidander** [comment]
> sorry guys, was busy. working on it

No worries!
