### ISSUE TITLE
feat: override config values via environment variables

### ISSUE THREAD

**Issue by jbergstroem** [ihippik/wal-listener#32]
It would be great to be able to override/set config values through environment variables. I believe viper supports this out of the box; combining `viper.SetEnvPrefix()` and `viper.AutomaticEnv()` could be a good start?

**Comment by ihippik** [comment]
agreed, mb viper would not be a bad choice for initializing the config.
I have a rather complex config structure so I didn’t use environment variables yet.

**Comment by emidander** [comment]
I would like this as well! For our Kubernetes setup it makes sense to override secrets (like Postgres password) using environement variables.

**Comment by ihippik** [comment]
sorry for the dellay, working on it

**Comment by ihippik** [comment]
https://github.com/ihippik/wal-listener/pull/45
