### ISSUE TITLE
Change log level for unknown oid type

### ISSUE THREAD

**Issue by JulesClaussen** [ihippik/wal-listener#39]
Hello,

We are using a lot of custom types that are parsed correctly. But we are spammed with the WARN "unknown oid type". On the other hand, we would like to keep the logs "event was sent" which is an INFO level.

Is there a way to change the "unknown oid type" error to DEBUG, as most of the time the parsing works fine? https://github.com/ihippik/wal-listener/blob/8622108af8fda31b183e402c74fc0b86c1dc9785/listener/wal_transaction.go#L134

Thank you,
Jules

**Comment by ihippik** [comment]
Hey Jules! Yes of course, I've wanted to do this for a long time
